{% set name = "loopdataconverter" %}

package:
  name: "{{ name|lower }}"
  version: "{{ environ.get('GIT_DESCRIBE_TAG', '') }}"

source:
  git_url: https://github.com/Loop3D/LoopDataConverter

build:
  number: 0
  script: "{{ PYTHON }} -m pip install ."

requirements:
  build:
    - {{ compiler('cxx') }}
    - numpy
  host:
    - pip
    - python
    - setuptools
    - numpy
  run:
    - numpy
    - python>=3.9
test:
  import:
    - numpy
    - pandas


about:
  home: "https://github.com/Loop3D/LoopDataConverter"
  license: MIT
  license_family: MIT
  license_file:
  summary: "Automatic conversion library of geological data (GIS) into Map2Loop and LoopStructural"
  doc_url: "https://loop3d.github.io/LoopDataConverter/"
  dev_url:

extra:
  recipe-maintainers:
    - rabii-chaarani