# Define the dictionaries for each column
fault_config = {
    "OBJECTID": {
        "alias": "OBJECTID",
        "visible": "N",
        "field_name": "OBJECTID",
        "field_order": 1,
        "description": "In a geodatabase feature class or standalone table within a geodatabase, the OBJECTID field contains the ObjectID, and the values start at one. In a shapefile, the FID field contains the ObjectID, and the values start at zero.",
        "type": "Numeric",
    },
    "SHAPE": {
        "alias": "SHAPE",
        "visible": "N",
        "field_name": "SHAPE",
        "field_order": 2,
        "description": "Polyline Geometry",
        "type": "Geometry",
    },
    "MSID": {
        "alias": "MSID",
        "visible": "Y",
        "field_name": "MSID",
        "field_order": 3,
        "description": "Unique identifier for GIS theme. For 1 250 000 scale the first two characters represent the mapsheet code. For 100 000 scale the first three characters represent the mapsheet code.",
        "type": "Char (10)",
    },
    "FaultType": {
        "alias": "FaultType",
        "visible": "Y",
        "field_name": "FaultType",
        "field_order": 4,
        "description": "Fault type.",
        "type": "Char (20)",
        "valid_lookup_terms": [
            "Normal",
            "Reverse",
            "Shear zone",
            "Strike-slip",
            "Thrust",
            "Unknown",
        ],
    },
    "FaultName": {
        "alias": "FaultName",
        "visible": "Y",
        "field_name": "FaultName",
        "field_order": 5,
        "description": "Fault name (if known).",
        "type": "Char (75)",
    },
    "DefZone": {
        "alias": "DefZone",
        "visible": "Y",
        "field_name": "DefZone",
        "field_order": 6,
        "description": "Name of shear/deformation zone containing the fault (if known).",
        "type": "Char (30)",
    },
    "Classification": {
        "alias": "Classification",
        "visible": "Y",
        "field_name": "Classification",
        "field_order": 7,
        "description": "Qualitative measure of accuracy of interpretation.",
        "type": "Char (30)",
        "valid_lookup_terms": [
            "Undefined",
            "Accurate",
            "Approximate",
            "Inferred",
            "Concealed",
            "Inferred-concealed",
            "Probable",
            "Speculative",
            "At Surface",
            "Mapped",
            "Interpreted",
        ],
    },
    "InterpSource": {
        "alias": "InterpSource",
        "visible": "Y",
        "field_name": "InterpSource",
        "field_order": 8,
        "description": "Source used for interpretation.",
        "type": "Char (64)",
        "valid_lookup_terms": [
            "Aerial photography",
            "Airborne magnetic data",
            "Airborne radiometric data",
            "Drilling data",
            "Electromagnetic data",
            "Geological interpretation/extrapolation",
            "Geological mapping",
            "Gravity data",
            "Resistivity survey",
            "Satellite imagery",
            "Seismic survey data",
            "Unknown",
        ],
    },
    "SenseDom": {
        "alias": "SenseDom",
        "visible": "Y",
        "field_name": "SenseDom",
        "field_order": 9,
        "description": "Dominant sense of movement of fault.",
        "type": "Char (20)",
        "valid_lookup_terms": ["Dextral", "Dip-slip", "None", "Sinistral", "Unknown"],
    },
    "SenseSub": {
        "alias": "SenseSub",
        "visible": "Y",
        "field_name": "SenseSub",
        "field_order": 10,
        "description": "Subdominant sense of movement of fault.",
        "type": "Char (20)",
        "valid_lookup_terms": ["Dextral", "Dip-slip", "None", "Sinistral", "Unknown"],
    },
    "Dip": {
        "alias": "Dip",
        "visible": "Y",
        "field_name": "Dip",
        "field_order": 11,
        "description": "Vertical (90°), Steep (>45°), Moderate (15°-45°), Shallow (5°-15°), Horizontal (<5°).",
        "type": "Char (20)",
        "valid_lookup_terms": [
            "Vertical",
            "Steep",
            "Moderate",
            "Shallow",
            "Horizontal",
        ],
    },
    "DipDirection": {
        "alias": "DipDirection",
        "visible": "Y",
        "field_name": "DipDirection",
        "field_order": 12,
        "description": "Compass bearing of dip direction.",
        "type": "Char (10)",
        "valid_lookup_terms": [
            "N",
            "E",
            "S",
            "W",
            "NE",
            "SE",
            "SW",
            "NW",
            "NNE",
            "ENE",
            "ESE",
            "SSE",
            "SSW",
            "WSW",
            "WNW",
            "NNW",
        ],
    },
    "Strike": {
        "alias": "Strike",
        "visible": "Y",
        "field_name": "Strike",
        "field_order": 13,
        "description": "Compass bearing of average strike direction of fault.",
        "type": "Char (10)",
    },
    "Displacement": {
        "alias": "Displacement",
        "visible": "Y",
        "field_name": "Displacement",
        "field_order": 14,
        "description": "Fault displacement in metres (m).",
        "type": "Char (20)",
        "valid_lookup_terms": ["1m-100m", "100m-1km", "1km-5km", ">5km"],
    },
    "FaultWidth": {
        "alias": "FaultWidth",
        "visible": "Y",
        "field_name": "FaultWidth",
        "field_order": 15,
        "description": "Width of the fault in metres.",
        "type": "Char (10)",
    },
    "FaultLength": {
        "alias": "FaultLength",
        "visible": "Y",
        "field_name": "FaultLength",
        "field_order": 16,
        "description": "Fault length classification in metres (m).",
        "type": "Char (20)",
        "valid_lookup_terms": [
            "Small (0-5km)",
            "Medium (5-30km)",
            "Large (30-100km)",
            "Regional (>100km)",
            "Unclassified",
        ],
    },
    "DefType": {
        "alias": "DefType",
        "visible": "Y",
        "field_name": "DefType",
        "field_order": 17,
        "description": "Fault zone fabric.",
        "type": "Char (30)",
        "valid_lookup_terms": [
            "Brittle",
            "Brittle-ductile",
            "Ductile",
            "Mylonitic",
            "Proto-mylonitic",
            "Breccia",
            "Cataclasite",
            "Unknown",
        ],
    },
    "Description": {
        "alias": "Description",
        "visible": "Y",
        "field_name": "Description",
        "field_order": 18,
        "description": "Free text description.",
        "type": "Char (254)",
    },
    "FeatureCodeDesc": {
        "alias": "Feature Code Description",
        "visible": "Y",
        "field_name": "FeatureCodeDesc",
        "field_order": 19,
        "description": "Feature code description.",
        "type": "Char (128)",
    },
    "FeatureCode": {
        "alias": "Feature Code",
        "visible": "Y",
        "field_name": "FeatureCode",
        "field_order": 20,
        "description": "",
        "type": "Integer (7)",
    },
    "SHAPE_Length": {
        "alias": "SHAPE_Length",
        "visible": "N",
        "field_name": "SHAPE_Length",
        "field_order": 21,
        "description": "",
        "type": "Numeric (Double)",
    },
}
