# Define the dictionaries for each column
fold_config = {
    "OBJECTID": {
        "alias": "OBJECTID",
        "visible": "N",
        "field_name": "OBJECTID",
        "field_order": 1,
        "description": "In a geodatabase feature class or standalone table within a geodatabase, the OBJECTID field contains the ObjectID, and the values start at one. In a shapefile, the FID field contains the ObjectID, and the values start at zero.",
        "type": "Numeric",
    },
    "SHAPE": {
        "alias": "SHAPE",
        "visible": "N",
        "field_name": "SHAPE",
        "field_order": 2,
        "description": "Polyline Geometry",
        "type": "Geometry",
    },
    "MSID": {
        "alias": "MSID",
        "visible": "Y",
        "field_name": "MSID",
        "field_order": 3,
        "description": "Unique identifier for GIS theme. For 1 250 000 scale the first two characters represent the mapsheet code. For 100 000 scale the first three characters represent the mapsheet code.",
        "type": "Char (10)",
    },
    "FoldType": {
        "alias": "FoldType",
        "visible": "Y",
        "field_name": "FoldType",
        "field_order": 4,
        "description": "Type of fold.",
        "type": "Char (30)",
        "valid_lookup_terms": [
            "Anticline",
            "Syncline",
            "Antiform",
            "Synform",
            "Monocline",
            "Monoform",
            "Neutral",
            "Fold axis",
            "Overturned syncline",
        ],
    },
    "FoldName": {
        "alias": "FoldName",
        "visible": "Y",
        "field_name": "FoldName",
        "field_order": 5,
        "description": "Fold name (if known).",
        "type": "Char (30)",
    },
    "Classification": {
        "alias": "Classification",
        "visible": "Y",
        "field_name": "Classification",
        "field_order": 6,
        "description": "Qualitative measure of accuracy of interpretation.",
        "type": "Char (30)",
        "valid_lookup_terms": [
            "Accurate",
            "Approximate",
            "Concealed",
            "Inferred",
            "Inferred-concealed",
            "Probable",
            "Speculative",
            "Undefined",
        ],
    },
    "InterpSource": {
        "alias": "InterpSource",
        "visible": "Y",
        "field_name": "InterpSource",
        "field_order": 7,
        "description": "Source used for interpretation.",
        "type": "Char (64)",
        "valid_lookup_terms": [
            "Aerial photography",
            "Airborne magnetic data",
            "Airborne radiometric data",
            "Drilling data",
            "Electromagnetic data",
            "Geological interpretation/extrapolation",
            "Geological mapping",
            "Gravity data",
            "Resistivity survey",
            "Satellite imagery",
            "Seismic survey data",
        ],
    },
    "AxialPlaneDipDir": {
        "alias": "AxialPlaneDipDir",
        "visible": "Y",
        "field_name": "AxialPlaneDipDir",
        "field_order": 8,
        "description": "Axial plane direction as a compass bearing.",
        "type": "Char (10)",
        "valid_lookup_terms": [
            "N",
            "E",
            "S",
            "W",
            "NE",
            "SE",
            "SW",
            "NW",
            "NNE",
            "ENE",
            "ESE",
            "SSE",
            "SSW",
            "WSW",
            "WNW",
            "NNW",
        ],
    },
    "AxialPlaneDip": {
        "alias": "AxialPlaneDip",
        "visible": "Y",
        "field_name": "AxialPlaneDip",
        "field_order": 9,
        "description": "Axial plane dip.",
        "type": "Char (20)",
        "valid_lookup_terms": ["Inclined", "Reclined", "Recumbent", "Upright"],
    },
    "InterlimbAngle": {
        "alias": "InterlimbAngle",
        "visible": "Y",
        "field_name": "InterlimbAngle",
        "field_order": 10,
        "description": "Fold tightness by approximate interlimb angle.",
        "type": "Char (20)",
        "valid_lookup_terms": [
            "gentle 180-120",
            "open 70-120",
            "close 30-70",
            "tight 0-30",
            "isoclinal 0",
        ],
    },
    "AxisPlungeDir": {
        "alias": "AxisPlungeDir",
        "visible": "Y",
        "field_name": "AxisPlungeDir",
        "field_order": 11,
        "description": "Plunge direction of fold axis as a compass bearing - use 2 directions if double-plunging, e.g. SE-NW.",
        "type": "Char (10)",
        "valid_lookup_terms": [
            "N",
            "E",
            "S",
            "W",
            "NE",
            "SE",
            "SW",
            "NW",
            "NNE",
            "ENE",
            "ESE",
            "SSE",
            "SSW",
            "WSW",
            "WNW",
            "NNW",
        ],
    },
    "AxisPlunge": {
        "alias": "AxisPlunge",
        "visible": "Y",
        "field_name": "AxisPlunge",
        "field_order": 12,
        "description": "Inclination of fold axis from horizontal: range in degrees (e.g. 20-40).",
        "type": "Char (10)",
    },
    "Eon": {
        "alias": "Eon",
        "visible": "Y",
        "field_name": "Eon",
        "field_order": 13,
        "description": "Eon name. Ref: yyyy ICS International Stratigraphic Chart",
        "type": "Char (30)",
    },
    "Era": {
        "alias": "Era",
        "visible": "Y",
        "field_name": "Era",
        "field_order": 14,
        "description": "Era name. Ref: yyyy ICS International Stratigraphic Chart",
        "type": "Char (30)",
    },
    "Period": {
        "alias": "Period",
        "visible": "Y",
        "field_name": "Period",
        "field_order": 15,
        "description": "Period name. Ref: yyyy ICS International Stratigraphic Chart.",
        "type": "Char (20)",
    },
    "Epoch": {
        "alias": "Epoch",
        "visible": "Y",
        "field_name": "Epoch",
        "field_order": 16,
        "description": "Epoch name. Ref: yyyy ICS International Stratigraphic Chart.",
        "type": "Char (40)",
    },
    "OrogenicEvent": {
        "alias": "OrogenicEvent",
        "visible": "Y",
        "field_name": "OrogenicEvent",
        "field_order": 17,
        "description": "Name of orogeny during which the fold formed.",
        "type": "Char (30)",
    },
    "DefEvent": {
        "alias": "DefEvent",
        "visible": "Y",
        "field_name": "DefEvent",
        "field_order": 18,
        "description": "Deformation event that formed the fold in local event terminology (D1, D2 etc)",
        "type": "Char (30)",
    },
    "FoldEvent": {
        "alias": "FoldEvent",
        "visible": "Y",
        "field_name": "FoldEvent",
        "field_order": 19,
        "description": "Fold event in local event terminology (F1, F2 etc). Numbers don't necessarily match with D events.",
        "type": "Char (30)",
    },
    "DefLater": {
        "alias": "DefLater",
        "visible": "Y",
        "field_name": "DefLater",
        "field_order": 20,
        "description": "Later fold event(s) that affected the fold.",
        "type": "Char (64)",
    },
    "FoldLength": {
        "alias": "FoldLength",
        "visible": "Y",
        "field_name": "FoldLength",
        "field_order": 21,
        "description": "Fold length classification in metres (m).",
        "type": "Char (20)",
        "valid_lookup_terms": [
            "Small (0-5km)",
            "Medium (5-30km)",
            "Large (30-100km)",
            "Regional (>100km)",
            "Unclassified",
        ],
    },
    "Description": {
        "alias": "Description",
        "visible": "Y",
        "field_name": "Description",
        "field_order": 22,
        "description": "Free text description.",
        "type": "Char (254)",
    },
    "FeatureCodeDesc": {
        "alias": "Feature Code Description",
        "visible": "Y",
        "field_name": "FeatureCodeDesc",
        "field_order": 23,
        "description": "Feature code description.",
        "type": "Char (128)",
    },
    "FeatureCode": {
        "alias": "Feature Code",
        "visible": "Y",
        "field_name": "FeatureCode",
        "field_order": 24,
        "description": "",
        "type": "Integer (7)",
    },
    "SHAPE_Length": {
        "alias": "SHAPE_Length",
        "visible": "N",
        "field_name": "SHAPE_Length",
        "field_order": 25,
        "description": "",
        "type": "Numeric (Double)",
    },
}
