# Define the dictionaries for each column
geology_config = {
    "OBJECTID": {
        "alias": "OBJECTID",
        "visible": "N",
        "field_name": "OBJECTID",
        "field_description": "In a geodatabase feature class or standalone table within a geodatabase, the OBJECTID field contains the ObjectID, and the values start at one. In a shapefile, the FID field contains the ObjectID, and the values start at zero.",
        "field_type": "Numeric",
    },
    "SHAPE": {
        "alias": "SHAPE",
        "visible": "N",
        "field_name": "SHAPE",
        "field_description": "Polyline Geometry",
        "field_type": "Geometry",
    },
    "MSID": {
        "alias": "MSID",
        "visible": "Y",
        "field_name": "MSID",
        "field_description": "Unique identifier for GIS theme. For 1 250 000 scale the first two characters represent the mapsheet code. For 100 000 scale the first three characters represent the mapsheet code.",
        "field_type": "Char (10)",
    },
    "Symbol": {
        "alias": "Symbol",
        "visible": "Y",
        "field_name": "Symbol",
        "field_description": "Geological symbol code taken from the source map or standard Geoscience Australia (GA) code.",
        "field_type": "Char (30)",
    },
    "MapSymbol": {
        "alias": "MapSymbol",
        "visible": "Y",
        "field_name": "MapSymbol",
        "field_description": "",
        "field_type": "Char (10)",
    },
    "Province": {
        "alias": "Province",
        "visible": "Y",
        "field_name": "Province",
        "field_description": "Common name of the geological province within a region.",
        "field_type": "Char (64)",
    },
    "Supergroup": {
        "alias": "Supergroup",
        "visible": "Y",
        "field_name": "Supergroup",
        "field_description": "Super Group or igneous Super Suite.",
        "field_type": "Char (64)",
    },
    "StratNoSupergroup": {
        "alias": "StratNoSupergroup",
        "visible": "Y",
        "field_name": "StratNoSupergroup",
        "field_description": "",
        "field_type": "Integer",
    },
    "GroupSuite": {
        "alias": "Group",
        "visible": "Y",
        "field_name": "Group",
        "field_description": "Group or igneous Suite name, Unassigned only if true.",
        "field_type": "Char (64)",
    },
    "StratNoGroupSuite": {
        "alias": "StratNoGroup",
        "visible": "Y",
        "field_name": "StratNoGroup",
        "field_description": "",
        "field_type": "Integer",
    },
    "Subgroup": {
        "alias": "Subgroup",
        "visible": "Y",
        "field_name": "Subgroup",
        "field_description": "Subgroup name.",
        "field_type": "Char (64)",
    },
    "StratNoSubgroup": {
        "alias": "StratNoSubgroup",
        "visible": "Y",
        "field_name": "StratNoSubgroup",
        "field_description": "",
        "field_type": "Integer",
    },
    "Formation": {
        "alias": "Formation",
        "visible": "Y",
        "field_name": "Formation",
        "field_description": "Formation or igneous Phase name.",
        "field_type": "Char (64)",
    },
    "StratNoFormation": {
        "alias": "StratNoFormation",
        "visible": "Y",
        "field_name": "StratNoFormation",
        "field_description": "",
        "field_type": "Integer",
    },
    "Member": {
        "alias": "Member",
        "visible": "Y",
        "field_name": "Member",
        "field_description": "Member or sub phase name.",
        "field_type": "Char (64)",
    },
    "StratNoMember": {
        "alias": "StratNoMember",
        "visible": "Y",
        "field_name": "StratNoMember",
        "field_description": "",
        "field_type": "Integer",
    },
    "Relationship": {
        "alias": "Relationship",
        "visible": "Y",
        "field_name": "Relationship",
        "field_description": "Relationship of the unit to other units.",
        "field_type": "Char (254)",
    },
    "Eon": {
        "alias": "Eon",
        "visible": "Y",
        "field_name": "Eon",
        "field_description": "Eon name. Ref: yyyy ICS International Stratigraphic Chart.",
        "field_type": "Char (30)",
    },
    "Era": {
        "alias": "Era",
        "visible": "Y",
        "field_name": "Era",
        "field_description": "Era name. Ref: yyyy ICS International Stratigraphic Chart.",
        "field_type": "Char (30)",
    },
    "Period": {
        "alias": "Period",
        "visible": "Y",
        "field_name": "Period",
        "field_description": "Period name. Ref: yyyy ICS International Stratigraphic Chart.",
        "field_type": "Char (30)",
    },
    "Epoch": {
        "alias": "Epoch",
        "visible": "Y",
        "field_name": "Epoch",
        "field_description": "Epoch name. Ref: yyyy ICS International Stratigraphic Chart.",
        "field_type": "Char (40)",
    },
    "Stage": {
        "alias": "Stage",
        "visible": "Y",
        "field_name": "Stage",
        "field_description": "Stage name. Ref: yyyy ICS International Stratigraphic Chart.",
        "field_type": "Char (64)",
    },
    "AgeMin": {
        "alias": "AgeMin",
        "visible": "Y",
        "field_name": "AgeMin",
        "field_description": "Minimum age for the unit in Ma (million years).",
        "field_type": "Integer",
    },
    "AgeMax": {
        "alias": "AgeMax",
        "visible": "Y",
        "field_name": "AgeMax",
        "field_description": "Maximum age for the unit in Ma (million years).",
        "field_type": "Integer",
    },
    "LithClass": {
        "alias": "LithClass",
        "visible": "Y",
        "field_name": "LithClass",
        "field_description": "Major rock classification e.g. Igneous, Sedimentary, Metamorphic.",
        "field_type": "Char (30)",
    },
    "RockCategory": {
        "alias": "RockCategory",
        "visible": "Y",
        "field_name": "RockCategory",
        "field_description": "Broad rock type classification e.g. Clastic sediment, Felsic intrusive.",
        "field_type": "Char (64)",
    },
    "LithPrim": {
        "alias": "LithPrim",
        "visible": "Y",
        "field_name": "LithPrim",
        "field_description": "Principal lithology of the unit.",
        "field_type": "Char (64)",
    },
    "LithSub": {
        "alias": "LithSub",
        "visible": "Y",
        "field_name": "LithSub",
        "field_description": "Subordinate lithology of the unit.",
        "field_type": "Char (64)",
    },
    "LithOther": {
        "alias": "LithOther",
        "visible": "Y",
        "field_name": "LithOther",
        "field_description": "Other lithologies listed in order of decreasing abundance.",
        "field_type": "Char (64)",
    },
    "Mineral1": {
        "alias": "Mineral1",
        "visible": "Y",
        "field_name": "Mineral1",
        "field_description": "Dominant mineral present.",
        "field_type": "Char (64)",
    },
    "Mineral2": {
        "alias": "Mineral2",
        "visible": "Y",
        "field_name": "Mineral2",
        "field_description": "Subdominant mineral.",
        "field_type": "Char (64)",
    },
    "Mineral3": {
        "alias": "Mineral3",
        "visible": "Y",
        "field_name": "Mineral3",
        "field_description": "Subdominant mineral.",
        "field_type": "Char (64)",
    },
    "LithDescription": {
        "alias": "LithDescription",
        "visible": "Y",
        "field_name": "LithDescription",
        "field_description": "Free text non-genetic lithological description of the unit. For complex unit, include individual description separated by '---', spread over LithDescn1, 2, and 3.",
        "field_type": "Char (1000)",
    },
    "ThicknessMax": {
        "alias": "ThicknessMax",
        "visible": "Y",
        "field_name": "ThicknessMax",
        "field_description": "Maximum thickness of the unit in metres.",
        "field_type": "Integer",
    },
    "ThicknessAvg": {
        "alias": "ThicknessAvg",
        "visible": "Y",
        "field_name": "ThicknessAvg",
        "field_description": "Average thickness of the unit in metres.",
        "field_type": "Integer",
    },
    "DepEnviron": {
        "alias": "DepEnviron",
        "visible": "Y",
        "field_name": "DepEnviron",
        "field_description": "Depositional environment of the unit e.g. shallow marine.",
        "field_type": "Char (64)",
    },
    "FossilAge": {
        "alias": "FossilAge",
        "visible": "Y",
        "field_name": "FossilAge",
        "field_description": "Age by biostratigraphic zone(s).",
        "field_type": "Char (128)",
    },
    "colourRGB": {
        "alias": "colourRGB",
        "visible": "Y",
        "field_name": "colourRGB",
        "field_description": "rgb colour value formatted rrr,ggg,bbb.",
        "field_type": "Char (11)",
    },
    "colourHEX": {
        "alias": "colourHEX",
        "visible": "Y",
        "field_name": "colourHEX",
        "field_description": "hex colour value formatted #abcdef.",
        "field_type": "Char (7)",
    },
    "patternCode": {
        "alias": "patternCode",
        "visible": "Y",
        "field_name": "patternCode",
        "field_description": "Original mapInfo_brush_pattern.",
        "field_type": "Integer",
    },
    "patternRGB": {
        "alias": "patternRGB",
        "visible": "Y",
        "field_name": "patternRGB",
        "field_description": "rgb colour value formatted rrr,ggg,bbb.",
        "field_type": "Char (11)",
    },
    "patternHEX": {
        "alias": "patternHEX",
        "visible": "Y",
        "field_name": "patternHEX",
        "field_description": "hex colour value formatted #abcdef.",
        "field_type": "Char (7)",
    },
}
