# Define the dictionaries for each column
structure_config = {
    "OBJECTID": {
        "alias": "OBJECTID",
        "visible": "N",
        "field_name": "OBJECTID",
        "field_order": 1,
        "description": "In a geodatabase feature class or standalone table within a geodatabase, the OBJECTID field contains the ObjectID, and the values start at one. In a shapefile, the FID field contains the ObjectID, and the values start at zero.",
        "type": "Numeric",
    },
    "SHAPE": {
        "alias": "SHAPE",
        "visible": "N",
        "field_name": "SHAPE",
        "field_order": 2,
        "description": "Polyline Geometry",
        "type": "Geometry",
    },
    "MSID": {
        "alias": "MSID",
        "visible": "Y",
        "field_name": "MSID",
        "field_order": 3,
        "description": "Unique identifier for GIS theme. For 1 250 000 scale the first two characters represent the mapsheet code. For 100 000 scale the first three characters represent the mapsheet code.",
        "type": "Char (10)",
    },
    "Latitude": {
        "alias": "Latitude",
        "visible": "Y",
        "field_name": "Latitude",
        "field_order": 5,
        "description": "",
        "type": "Decimal (3,6)",
    },
    "Longitude": {
        "alias": "Longitude",
        "visible": "Y",
        "field_name": "Longitude",
        "field_order": 6,
        "description": "",
        "type": "Decimal (3,6)",
    },
    "Datum": {
        "alias": "Datum",
        "visible": "Y",
        "field_name": "Datum",
        "field_order": 7,
        "description": "",
        "type": "Char (5)",
    },
    "ObsType": {
        "alias": "ObsType",
        "visible": "Y",
        "field_name": "ObsType",
        "field_order": 8,
        "description": "Observation type.",
        "type": "Char (20)",
        "valid_lookup_terms": [
            "Bedding",
            "Cleavage",
            "Faulting",
            "Folding",
            "Foliation",
            "Geophysical",
            "Igneous banding",
            "Lineation",
        ],
    },
    "InterpSource": {
        "alias": "InterpSource",
        "visible": "Y",
        "field_name": "InterpSource",
        "field_order": 9,
        "description": "Source used for interpretation.",
        "type": "Char (64)",
        "valid_lookup_terms": [
            "Aerial photography",
            "Airborne magnetic data",
            "Airborne radiometric data",
            "Drilling data",
            "Electromagnetic data",
            "Geological interpretation/extrapolation",
            "Geological mapping",
            "Gravity data",
            "Resistivity survey",
            "Satellite imagery",
            "Seismic survey data",
            "Unknown",
        ],
    },
    "LocMethod": {
        "alias": "LocMethod",
        "visible": "Y",
        "field_name": "LocMethod",
        "field_order": 10,
        "description": "Method used to spatially locate position.",
        "type": "Char (32)",
        "valid_lookup_terms": [
            "100K Map",
            "250K Map",
            "GPS",
            "Aerial photography",
            "Company report",
            "Unknown",
        ],
    },
    "LocAccuracy": {
        "alias": "LocAccuracy",
        "visible": "Y",
        "field_name": "LocAccuracy",
        "field_order": 11,
        "description": "Indicates numerical accuracy of location.",
        "type": "Char (20)",
        "valid_lookup_terms": [
            "<5m",
            "5 to 20m",
            "20 to 100m",
            "100 to 200m",
            ">200m",
            "Unknown",
        ],
    },
    "DipDirection": {
        "alias": "DipDirection",
        "visible": "Y",
        "field_name": "DipDirection",
        "field_order": 12,
        "description": "Compass bearing of dip direction. Dip direction (plane), plunge direction (lineation), younging direction, palaeocurrent direction. If horizontal plane, azimuth = 360",
        "type": "Integer",
    },
    "Dip": {
        "alias": "Dip",
        "visible": "Y",
        "field_name": "Dip",
        "field_order": 13,
        "description": "Dip or inclination (0-90 degrees).",
        "type": "Integer",
    },
    "DipEstimate": {
        "alias": "DipEstimate",
        "visible": "Y",
        "field_name": "DipEstimate",
        "field_order": 14,
        "description": "Inclination of plane estimated from aerial photography",
        "type": "Char (20)",
    },
    "Description": {
        "alias": "Description",
        "visible": "Y",
        "field_name": "Description",
        "field_order": 15,
        "description": "Free text description of structural feature.",
        "type": "Char (254)",
    },
    "FeatureCodeDesc": {
        "alias": "Feature Code Description",
        "visible": "Y",
        "field_name": "FeatureCodeDesc",
        "field_order": 16,
        "description": "Feature code description.",
        "type": "Char (128)",
    },
    "FeatureCode": {
        "alias": "Feature Code",
        "visible": "Y",
        "field_name": "FeatureCode",
        "field_order": 17,
        "description": "",
        "type": "Integer (7)",
    },
}
